<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>1de2185c-a698-4fd8-96d8-8cb9dc92d324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-bypJrT.kAFndp.next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbca221e-5979-4e1e-ab93-107a076c7f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>4d0a84e6-3b88-49e6-b71c-371c387616af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bypJrT kAFndp next</value>
      <webElementGuid>02fadf8d-7d75-43bd-b350-99343799f3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Press Enter ↵Next</value>
      <webElementGuid>25e72f1c-dcea-46f2-b029-0f173301e0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer hCtYxp sc-guJBdh iNaETe noPadding&quot;]/div[@class=&quot;sc-fqkvVR hgaxwi&quot;]/div[@class=&quot;sc-klVQfs ccqzuV&quot;]/div[@class=&quot;sc-bypJrT kAFndp next&quot;]</value>
      <webElementGuid>b11d2287-3dca-4976-a7b6-fd164d9ad2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]</value>
      <webElementGuid>f48650eb-6a4a-4c12-8fbc-56d30b86664c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[1]</value>
      <webElementGuid>2c81191d-1656-4296-9ce2-e086e9094846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>81a4011c-e3c6-4f44-8246-105391502a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Press Enter ↵Next' or . = 'Press Enter ↵Next')]</value>
      <webElementGuid>72ee35dd-daf2-46d8-b078-284967eb11ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
