<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Education-Secondary School</name>
   <tag></tag>
   <elementGuidId>3fbadb3a-1521-4765-bb28-52724bc8190d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-9-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Secondary School')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2dcfe67-eb7e-4df5-a206-c073dee2a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-2d7khs-option</value>
      <webElementGuid>cf31ab72-c254-4061-9dd9-995650a26419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-9-option-1</value>
      <webElementGuid>69ecb058-af9e-4631-baef-6958abea05fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>20576be7-e1b8-4053-8ea4-b442e0406192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secondary School</value>
      <webElementGuid>b4278bc3-c146-4e31-8796-9cceb0428ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-9-option-1&quot;)</value>
      <webElementGuid>f52c0fe2-0b4c-4299-a17a-b372d59861ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-9-option-1']</value>
      <webElementGuid>d5fc05ad-ebee-4276-9f84-e5daf8a52e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>fdfcd610-4a64-452c-9c23-4547df5e8225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Qualification'])[1]/following::div[1]</value>
      <webElementGuid>5922e9b6-4725-4323-b599-530c89c4e62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[1]/following::div[7]</value>
      <webElementGuid>55ca8220-d4ac-44c1-8bb9-c6712d46a4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industry or Trade Training'])[1]/preceding::div[1]</value>
      <webElementGuid>d7b5f98c-99d6-418b-88b0-1786377ccfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Qualification'])[1]/preceding::div[2]</value>
      <webElementGuid>504357b1-4264-4432-b2fe-3462dc06e470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Secondary School']/parent::*</value>
      <webElementGuid>135d894d-30ff-480d-8c4a-9eec8f1cbc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>9276177a-a55f-4f10-bd66-6558a828bc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-9-option-1' and (text() = 'Secondary School' or . = 'Secondary School')]</value>
      <webElementGuid>7bc761bd-3077-49a4-8b94-c6369689db21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
