<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Respondents</name>
   <tag></tag>
   <elementGuidId>e225626e-a789-418d-8b9b-779cd057a4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Sidebar__StyledTab-sc-h8wc3d-5.aPaIO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@from=&quot;/respondents&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7aafbd32-c02c-42aa-ad79-d11bb4cdebab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>189f376d-a55f-41cb-9c90-5a13462a3381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>from</name>
      <type>Main</type>
      <value>/respondents</value>
      <webElementGuid>f93935cd-9661-4403-b29c-10f24284aef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isactive</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68ac2fcb-ddfb-475f-bbfc-8c7575c7ccd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Sidebar__StyledTab-sc-h8wc3d-5 aPaIO</value>
      <webElementGuid>79d4c013-53c7-481b-8ba2-7681d1280489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/respondents</value>
      <webElementGuid>720ad064-54aa-41ac-9903-cbfe594effc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Respondents</value>
      <webElementGuid>41211c9a-197b-472b-8b44-bb0a68cbc0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/nav[@class=&quot;Sidebar__SidebarContainer-sc-h8wc3d-1 jHVVbs&quot;]/div[@class=&quot;Sidebar__TabsList-sc-h8wc3d-2 gUAEly&quot;]/div[1]/a[@class=&quot;Sidebar__StyledTab-sc-h8wc3d-5 aPaIO&quot;]</value>
      <webElementGuid>9659ef13-f4a9-4780-8434-5fe300a6eb99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/nav/div/div/a</value>
      <webElementGuid>ff597952-32df-4dec-9bb8-63d5a22efe82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/preceding::a[1]</value>
      <webElementGuid>f77c1ad1-7919-49cb-8d31-f298581b90c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/respondents')]</value>
      <webElementGuid>131b4b3f-0e3e-4414-b12c-9a7dde54c7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>b5416180-fa02-474c-b5a0-d240be70533d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/respondents' and (text() = 'Respondents' or . = 'Respondents')]</value>
      <webElementGuid>23c016c8-5424-4961-aeec-79620a480845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
