<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Projects</name>
   <tag></tag>
   <elementGuidId>9fbdec4f-afb8-41e4-94fc-a11c58efac82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/projects&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.Sidebar__StyledTab-sc-h8wc3d-5.jCGeiA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dbbd84b4-cbc5-4baf-a61d-b5d384f33235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>from</name>
      <type>Main</type>
      <value>/respondents</value>
      <webElementGuid>a6e04c69-b165-4557-b496-82236541184b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isactive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb2a8895-aaa8-404b-a856-3c653b2c3eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Sidebar__StyledTab-sc-h8wc3d-5 jCGeiA</value>
      <webElementGuid>0ea41446-eef7-4328-b1cc-5367375b5fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/projects</value>
      <webElementGuid>0ac0f863-4bbb-460f-b379-1fe1f3df9776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projects</value>
      <webElementGuid>73af9d94-cbc0-41e6-b265-3a3328c96675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/nav[@class=&quot;Sidebar__SidebarContainer-sc-h8wc3d-1 jHVVbs&quot;]/div[@class=&quot;Sidebar__TabsList-sc-h8wc3d-2 gUAEly&quot;]/div[1]/a[@class=&quot;Sidebar__StyledTab-sc-h8wc3d-5 jCGeiA&quot;]</value>
      <webElementGuid>787e414a-4379-4282-9124-837065f1a8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/nav/div/div/a[2]</value>
      <webElementGuid>89a3324b-7fce-4795-b160-684013dd774e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respondents'])[1]/following::a[1]</value>
      <webElementGuid>8585709c-d7bd-4e58-8e46-abd7f505045a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invites'])[1]/preceding::a[1]</value>
      <webElementGuid>fcc57f53-b45b-42cc-bd84-c65f8487addf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/projects')]</value>
      <webElementGuid>7bfc43d3-e876-44f4-bb9f-1cd6f903f623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>2b3d8f70-fcd5-4cd8-a9bc-74428a6ae9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/projects' and (text() = 'Projects' or . = 'Projects')]</value>
      <webElementGuid>ddd86434-7e2b-414d-b516-d0a1b4d489df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
