<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add new project</name>
   <tag></tag>
   <elementGuidId>380162ec-53a6-4f23-92f8-770bb67c209b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//span[contains(text(),'new')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Button__BaseButton-sc-3twruo-0.Button__RoundedButton-sc-3twruo-3.hTGRvA.PageWrapper__StyledButton-sc-10mepnc-5.fmhPkK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d547c6c-8a19-4dff-a064-e0e7d3feb5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e9ececf-d1f2-40df-95a6-c91f40500219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__BaseButton-sc-3twruo-0 Button__RoundedButton-sc-3twruo-3 hTGRvA PageWrapper__StyledButton-sc-10mepnc-5 fmhPkK</value>
      <webElementGuid>6a19906a-5304-42b4-a60f-25824a552da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47403fd6-8380-40bc-bf84-34bf9c4b7fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add new project</value>
      <webElementGuid>cfb7a597-bcde-4e04-a422-937fd5f5bb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;PageWrapper__Header-sc-10mepnc-1 eIEpjo&quot;]/div[@class=&quot;PageWrapper__ButtonsWrapper-sc-10mepnc-4 bLoDnc&quot;]/button[@class=&quot;Button__BaseButton-sc-3twruo-0 Button__RoundedButton-sc-3twruo-3 hTGRvA PageWrapper__StyledButton-sc-10mepnc-5 fmhPkK&quot;]</value>
      <webElementGuid>f1c984a5-b926-483e-9045-b834f76d3c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>21abeb81-9878-4548-a600-6e915099bb6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>95ae16e0-8b0b-49f3-8970-ccab1d7e2f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::button[1]</value>
      <webElementGuid>77178cf6-59fa-4622-b099-3051ad6851fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[1]</value>
      <webElementGuid>c34055c5-6aee-4558-b1f1-3942a9abfe71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::button[1]</value>
      <webElementGuid>fd87e8c5-2968-4b11-a145-d0b8fc452724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/button</value>
      <webElementGuid>e921b6a1-b81c-4b1e-89ca-acca547bc474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add new project' or . = 'Add new project')]</value>
      <webElementGuid>455151e0-44c5-4348-ba13-df3ae5f5e8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
