<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_S_DateSelect_Start of Month</name>
   <tag></tag>
   <elementGuidId>3343b12d-3342-4fc1-b234-c8d536a4000c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'rdrMonths')]//button[contains(@class,'rdrDayStartOfMonth')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.DateSelect__BgDrop-sc-s4e42t-6.htWjlg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3557358-478a-4e03-99ef-e0c0653db1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DateSelect__BgDrop-sc-s4e42t-6 htWjlg</value>
      <webElementGuid>c2820479-c7bf-46d7-b710-924550dc3d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 bASsOq AddRespondentModal__StyledModal-sc-gv2eix-0 cbZrEP&quot;]/form[@class=&quot;AddRespondentForm__Form-sc-nyr9r3-0 AQdLQ&quot;]/div[@class=&quot;AddRespondentForm__InputsHolder-sc-nyr9r3-1 jRoXFq&quot;]/div[6]/div[@class=&quot;DateSelect__OuterContainer-sc-s4e42t-0 deRUpa AddRespondentForm__DatePicker-sc-nyr9r3-5 bcNhJZ&quot;]/div[@class=&quot;DateSelect__BgDrop-sc-s4e42t-6 htWjlg&quot;]</value>
      <webElementGuid>c3a999bc-5686-4ea0-8bbb-4c0e589b3676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[6]/div/div[2]</value>
      <webElementGuid>9038583e-94cc-48d5-ad95-d4f2420c17e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[6]/div/div[2]</value>
      <webElementGuid>bb026ca0-f382-4694-961c-222aed82aa7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
