<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_Input-sc-1cu1w4j-2 jNDyqd</name>
   <tag></tag>
   <elementGuidId>ee1ca4aa-c2c1-4311-9afe-54539d6e50b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.DateSelect__OuterContainer-sc-s4e42t-0.deRUpa.AddRespondentForm__DatePicker-sc-nyr9r3-5.bcNhJZ > div.DateSelect__InputsContainer-sc-s4e42t-1.nGnyq > div.DateSelect__CalendarWrapper-sc-s4e42t-2.iwZlzq > div.Input__Container-sc-1cu1w4j-0.giaEKD.DateSelect__StyledInput-sc-s4e42t-5.fXliX > div.Input__InputWrapper-sc-1cu1w4j-1.jPeivJ > input.Input-sc-1cu1w4j-2.jNDyqd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>702c0a82-4f32-48bc-be91-bef3c0636a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>6d5d280e-cf6f-44bf-af84-3b9cf6de6172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1cu1w4j-2 jNDyqd</value>
      <webElementGuid>3fa97143-03e6-4885-bc1c-6f666a53ae63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 bASsOq AddRespondentModal__StyledModal-sc-gv2eix-0 cbZrEP&quot;]/form[@class=&quot;AddRespondentForm__Form-sc-nyr9r3-0 AQdLQ&quot;]/div[@class=&quot;AddRespondentForm__InputsHolder-sc-nyr9r3-1 jRoXFq&quot;]/div[6]/div[@class=&quot;DateSelect__OuterContainer-sc-s4e42t-0 deRUpa AddRespondentForm__DatePicker-sc-nyr9r3-5 bcNhJZ&quot;]/div[@class=&quot;DateSelect__InputsContainer-sc-s4e42t-1 nGnyq&quot;]/div[@class=&quot;DateSelect__CalendarWrapper-sc-s4e42t-2 iwZlzq&quot;]/div[@class=&quot;Input__Container-sc-1cu1w4j-0 giaEKD DateSelect__StyledInput-sc-s4e42t-5 fXliX&quot;]/div[@class=&quot;Input__InputWrapper-sc-1cu1w4j-1 jPeivJ&quot;]/input[@class=&quot;Input-sc-1cu1w4j-2 jNDyqd&quot;]</value>
      <webElementGuid>53418157-2ba7-4ed4-9884-f4021668f112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[17]</value>
      <webElementGuid>5fcd27d1-9502-4a88-a8fe-0c0a2261b377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[6]/div/div/div/div/div/input</value>
      <webElementGuid>8c1950fb-4104-4e48-a5f4-6e1d70510493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[6]/div/div/div/div/div/input</value>
      <webElementGuid>88a088b8-a713-4ede-a111-43b87cfcf961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Date of Birth']</value>
      <webElementGuid>af0463f8-1f69-4465-9052-f14b5880acce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
