<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leftside_menu</name>
   <tag></tag>
   <elementGuidId>7754f312-3a07-426e-82c4-989ed66f4f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/nav/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Sidebar__TabsList-sc-h8wc3d-2.gUAEly > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70838573-f785-4210-a3df-bf564dbdc59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RespondentsProjectsInvites56ReportsSettings</value>
      <webElementGuid>1848fe75-2db2-4a58-8021-9868267f9410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/nav[@class=&quot;Sidebar__SidebarContainer-sc-h8wc3d-1 jHVVbs&quot;]/div[@class=&quot;Sidebar__TabsList-sc-h8wc3d-2 gUAEly&quot;]/div[1]</value>
      <webElementGuid>a2dd7f92-5466-4afa-b6a3-4ba6e534c74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/nav/div/div</value>
      <webElementGuid>da4a1877-278a-4eee-a8d4-0bbfced774c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div</value>
      <webElementGuid>d718ccc8-d087-4aa7-b3c6-679c5cb39e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'RespondentsProjectsInvites56ReportsSettings' or . = 'RespondentsProjectsInvites56ReportsSettings')]</value>
      <webElementGuid>d7eacf76-d187-4e92-b21e-a8c7ad615831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
