<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>14788b73-219e-4d7d-ab0f-34a5461c5d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rodal-dialog.rodal-fade-enter > div.NewModal__Container-sc-1b0fhaf-0.cDYLtF.ConfirmationModal__StyledModal-sc-4vqn02-0.dwMPZO > div.ConfirmationModal__ButtonsWrapper-sc-4vqn02-2.iLzRyL > button.Button__BaseButton-sc-3twruo-0.Button__PrimaryButton-sc-3twruo-1.lfZVwD.ConfirmationModal__StyledButton-sc-4vqn02-3.eSqPeB</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[p[contains(text(),'delete selected respondents')]]//button[span[contains(text(),'Yes')]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fb18cc1-224e-4290-a683-cb6574221261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>66341aab-ef1b-4c72-b91d-ad621647dcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD ConfirmationModal__StyledButton-sc-4vqn02-3 eSqPeB</value>
      <webElementGuid>2dedf4cb-db84-47ab-b2d7-1ec8847589fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>60ece2e0-1830-4c48-8fef-5b80ccfb0494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 cDYLtF ConfirmationModal__StyledModal-sc-4vqn02-0 dwMPZO&quot;]/div[@class=&quot;ConfirmationModal__ButtonsWrapper-sc-4vqn02-2 iLzRyL&quot;]/button[@class=&quot;Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD ConfirmationModal__StyledButton-sc-4vqn02-3 eSqPeB&quot;]</value>
      <webElementGuid>eeaf934c-a9be-45b5-aede-a61c4fb1c085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[7]/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>1668a0f4-6c15-4f7d-b4d2-7786ff48ca67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::button[1]</value>
      <webElementGuid>07069f4f-a911-4587-942d-3f65cf09df96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete respondent'])[1]/following::button[2]</value>
      <webElementGuid>2e0ca5b9-b3b5-48a0-a195-75519064a2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove respondents from group'])[1]/preceding::button[1]</value>
      <webElementGuid>a7a5cabc-3331-4c1e-a081-003d2acd9e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>d3e60af1-3c19-4eb7-856e-7b7f5ee62547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>1402e285-b47d-4b66-96a3-1edddf73fa01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
