<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Empty search result</name>
   <tag></tag>
   <elementGuidId>744d2540-4851-4a40-a13c-180fad964543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.Respondents__EmptyMessage-sc-1bhwmih-4.iAlUde</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[contains(@class,'Respondents__EmptyMessage')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c5d89123-1f11-4c37-b39a-03d811aa1f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Respondents__EmptyMessage-sc-1bhwmih-4 iAlUde</value>
      <webElementGuid>d4bd9831-d460-4246-837e-ed4d2d5d1b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sorry, we could not find any respondents</value>
      <webElementGuid>f53151f9-1005-4bc6-bf54-9284bf3b6928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;Table__TableStyles-sc-12cd1gg-0 gYKZmf Respondents__StyledTable-sc-1bhwmih-0 iqoBDF&quot;]/div[@class=&quot;Respondents__EmptyMessageWrapper-sc-1bhwmih-3 bRKrtS&quot;]/p[@class=&quot;Respondents__EmptyMessage-sc-1bhwmih-4 iAlUde&quot;]</value>
      <webElementGuid>d784c298-edab-45ff-9b3e-4af04aa79f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[5]/div/div/div/p</value>
      <webElementGuid>6b359aa1-6638-476b-ad81-28534b840d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete respondent'])[1]/preceding::p[1]</value>
      <webElementGuid>90e0bf1b-cf7a-4561-9369-bcddfc59d1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::p[2]</value>
      <webElementGuid>5f8de856-7d6a-4c13-a795-a333b5aa2ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sorry, we could not find any respondents']/parent::*</value>
      <webElementGuid>52ab5ba2-5198-445a-ad31-4696c0c28861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/p</value>
      <webElementGuid>b31f066e-f2f3-4c8d-a028-0e9c71180842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sorry, we could not find any respondents' or . = 'Sorry, we could not find any respondents')]</value>
      <webElementGuid>b0479249-e44e-456f-8802-52e823710bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
