<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assessment Session Details_invitationId</name>
   <tag></tag>
   <elementGuidId>1ef2a5d7-f811-4c66-be7a-7831d82f8e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e20abc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e20abc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0738e3d-74a2-425c-b732-8d74bbf6a6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5543ed9-8ca1-4a0a-9439-552a89939908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e20abc</value>
      <webElementGuid>4ff9e8ae-126c-4f2b-83bc-983cb34cd96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3c4f3402-e126-4ffe-913d-4550fe6ac86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invitationId</value>
      <webElementGuid>a6774b6f-e987-40f8-a134-c021fa179562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eDPEul WbSWh</value>
      <webElementGuid>bf69c41a-4cdc-4178-bd4d-1cfdae21f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>83d9b012-0150-4d19-af9c-ea47ea24c23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e20abc&quot;)</value>
      <webElementGuid>13eadc8a-88b0-414f-90cc-f5d024a37376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e20abc']</value>
      <webElementGuid>c25b7f89-57d3-4c92-b7b2-f66adb0cb67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/input</value>
      <webElementGuid>cf825afe-0681-423b-a132-ed4d51033cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>724f4192-7a13-4807-828f-81e926b3de82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'e20abc' and @name = 'invitationId']</value>
      <webElementGuid>91b3dbb7-3cb1-4740-b9dd-fd349032fc50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
