<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invitation Id_respondentId</name>
   <tag></tag>
   <elementGuidId>e177de5b-ce07-468c-b7b2-df3fb4214cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#22jn8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='22jn8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38fa87b8-f72e-4f14-b818-3ffb4aabe01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17df162b-c69a-4744-b7e2-76f75350de09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22jn8</value>
      <webElementGuid>383f879d-534b-4032-a917-72b351852339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc4feb1b-28ca-4fd1-90a2-8a60e7b598bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>respondentId</value>
      <webElementGuid>a2ddc7cf-10d8-4d0b-b50f-caa399908cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eDPEul WbSWh</value>
      <webElementGuid>15be447d-db6c-460b-b7b1-aa626faa210a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>16297541-b882-4903-be65-601c3bddafbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22jn8&quot;)</value>
      <webElementGuid>17bf1ca0-c7de-4d60-9041-eefffda08ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='22jn8']</value>
      <webElementGuid>9831d271-8090-4a43-9ba2-d6c4c1ddb33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>eba44573-5ac1-44dc-9429-276b13fdf8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>e353661b-70c4-4ab9-ae34-0e71ea82fe08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '22jn8' and @name = 'respondentId']</value>
      <webElementGuid>02b17c1f-8f0f-492e-b29c-776451c80cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
