<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>f2be07b3-08b7-4b17-aa19-040c4453d4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-jsJBEP.DIphc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),'继续')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>580c03b7-562a-46bf-9079-06f16143d30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4cd5d89-74f3-4dd3-9d51-40f7f3f4d521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jsJBEP DIphc</value>
      <webElementGuid>eefb4865-2f18-4b32-99b4-6d6330505b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>继续</value>
      <webElementGuid>3aac1741-8f81-471c-a70d-6cc0c2fd579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer eSldpq sc-eBMEME krWXPs&quot;]/div[@class=&quot;sc-eqUAAy hAjgGB sc-cWSHoV liDRQq&quot;]/div[@class=&quot;sc-iGgWBj gYhruk&quot;]/div[@class=&quot;sc-aXZVg jflRja sc-fhzFiK jUHvFY&quot;]/button[@class=&quot;sc-jsJBEP DIphc&quot;]</value>
      <webElementGuid>9c7d3174-6a2e-45a7-bd57-f8c0d44b516b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>0e1ff03c-c3f7-4188-9d3a-12d8ab5f0192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>3b565731-c487-4e58-bc50-877ee46a9002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[1]/following::button[1]</value>
      <webElementGuid>ad39674a-a4ce-4986-ad12-6505307f1e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我接受'])[2]/following::button[2]</value>
      <webElementGuid>51c39464-8712-4d47-a4b6-63715f99953c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='继续']/parent::*</value>
      <webElementGuid>138ece25-5859-4895-bd82-ced656f7b435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>a282a08c-ccb1-4400-8431-f1262d6119e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '继续' or . = '继续')]</value>
      <webElementGuid>e79ea4ea-6f18-4efe-aa23-06b101b28d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
