<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Agriculture, Forestry and Fishing</name>
   <tag></tag>
   <elementGuidId>e0bd2491-fd20-4f10-91ac-2c9fa6110bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-13-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-13-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14e774ab-c6a3-4f08-a3cc-494e91b9257c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-2d7khs-option</value>
      <webElementGuid>5fb91136-5af8-44a9-9c1f-da6f609f8571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-13-option-1</value>
      <webElementGuid>1082b670-80ee-40ee-b339-a3be4e5c3cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>03ee846e-dfa2-4182-942b-8c7cbb2e57d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agriculture, Forestry and Fishing</value>
      <webElementGuid>46525814-e58a-4191-95d4-a866431c4ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-13-option-1&quot;)</value>
      <webElementGuid>e65c1020-c5bf-48b3-9d6e-60a5af37607c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-13-option-1']</value>
      <webElementGuid>5962d915-40a5-475a-b91f-4b08f6e5257d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[6]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>3831b6bf-f4b1-4cb1-890d-090c76b4eaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrative and Support Service'])[1]/following::div[1]</value>
      <webElementGuid>92747e77-e022-4a43-9d2b-0f7ca488e1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industry'])[1]/following::div[7]</value>
      <webElementGuid>b725425e-d25e-4e0e-9e66-f6dfa7ff6748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arts, Entertainment and Recreation'])[1]/preceding::div[1]</value>
      <webElementGuid>61ba0532-c01b-4952-8c17-e5a4f820c14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banking &amp; Finance'])[1]/preceding::div[2]</value>
      <webElementGuid>088f06c9-77ac-4265-a808-57e1e95bccbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agriculture, Forestry and Fishing']/parent::*</value>
      <webElementGuid>10e76416-bc10-45b3-a349-d7ddc8f65b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[6]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>a6d60c91-b498-40d1-a8c4-81b91ad124de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-13-option-1' and (text() = 'Agriculture, Forestry and Fishing' or . = 'Agriculture, Forestry and Fishing')]</value>
      <webElementGuid>1a6f8124-e331-4c04-bd7e-aa7b3a4ad5c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
