<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add ideal profile</name>
   <tag></tag>
   <elementGuidId>b0c85b82-6ac4-43db-ab85-8791b9bb47b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button__BaseButton-sc-3twruo-0.Button__RoundedButton-sc-3twruo-3.hTGRvA.PageWrapper__StyledButton-sc-10mepnc-5.fmhPkK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button/span[contains(text(),'Add ideal profile')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e084b1ac-cdf7-48cf-bc9c-7a836b1e752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ac41243-73e9-4050-8f3f-e2e838e5d1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__BaseButton-sc-3twruo-0 Button__RoundedButton-sc-3twruo-3 hTGRvA PageWrapper__StyledButton-sc-10mepnc-5 fmhPkK</value>
      <webElementGuid>69d54cb0-fccf-47f4-9881-8d3406b02b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56038ba5-3e9f-4941-be70-ac5e5fde5124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add ideal profile</value>
      <webElementGuid>7961205e-8665-4835-9097-5c6a75f22158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;PageWrapper__Header-sc-10mepnc-1 eIEpjo&quot;]/div[@class=&quot;PageWrapper__ButtonsWrapper-sc-10mepnc-4 bLoDnc&quot;]/button[@class=&quot;Button__BaseButton-sc-3twruo-0 Button__RoundedButton-sc-3twruo-3 hTGRvA PageWrapper__StyledButton-sc-10mepnc-5 fmhPkK&quot;]</value>
      <webElementGuid>9b996253-00e1-4122-8236-b9417f23b603</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f8982a49-95aa-45c3-96d6-5cb588e8969f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>3cf52d5e-ce44-43ec-a3fb-6dbfc74b12cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment Settings'])[1]/following::button[1]</value>
      <webElementGuid>d6d14181-bb89-4b97-bd7c-e659876112bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::button[2]</value>
      <webElementGuid>015d23c5-7717-40d3-a1b1-2518a602e694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::button[1]</value>
      <webElementGuid>6f887d18-a8bb-45e6-94b7-a00b4da9f5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/button</value>
      <webElementGuid>d30cfc9b-c17e-4b8b-ad0b-133bc85e3335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Add ideal profile' or . = 'Add ideal profile')]</value>
      <webElementGuid>0803b376-a601-4ae5-b503-14239caf4b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
