<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Group</name>
   <tag></tag>
   <elementGuidId>4bd89d87-f32d-4b5a-a955-2ba0f06bee23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1gtu0rj-indicatorContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'-menu')]//div[contains(@id,'select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc70cd42-b5db-4b66-8b96-3ce7f65a9b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>815918af-0a6b-41d0-b6ab-500d1dde4773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1gtu0rj-indicatorContainer</value>
      <webElementGuid>f1c909c9-d40e-47c0-8244-11fefa25c174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 cDYLtF AddIdealProfile__StyledModal-sc-br5c8r-0 cghSzL&quot;]/div[@class=&quot;AddIdealProfile__FormSection-sc-br5c8r-1 iwvPzJ&quot;]/div[@class=&quot;Select__SelectWrapper-sc-gxrqw-0 kIwUsj AddIdealProfile__StyledSelect-sc-br5c8r-3 gWILdK&quot;]/div[@class=&quot;css-1be007b-container&quot;]/div[@class=&quot;css-1e99al4-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-1gtu0rj-indicatorContainer&quot;]</value>
      <webElementGuid>b8cdb4dd-0b88-42ba-8490-b561552231a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div/div[7]/div[2]/div/div[2]/div[5]/div/div/div[2]/div</value>
      <webElementGuid>ec6916d1-c41e-46b2-856b-094eb896b007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::div[2]</value>
      <webElementGuid>141994cd-65b5-4018-8af3-359a84450a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NZ Accounting Industry'])[1]/following::div[9]</value>
      <webElementGuid>3eb1e544-3377-4979-826d-be669e7e5771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group A (With 15FQ+ Result)'])[1]/preceding::div[1]</value>
      <webElementGuid>7b3ded5a-d0a7-489a-bc2c-4dc52fea02bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group B'])[1]/preceding::div[3]</value>
      <webElementGuid>7e321537-6200-4e13-a95d-7f5f2d79c400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div</value>
      <webElementGuid>78bfd67b-a194-42c7-ac76-ee065f7a22f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
