<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rating</name>
   <tag></tag>
   <elementGuidId>b9e389eb-8421-4a9c-806e-e1b851e09e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-slider-handle.rc-slider-handle-click-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'CustomForm__StyledRow')][1]//span[@class=&quot;rc-slider-dot&quot;][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5518b58f-ed6a-4424-852c-4d9346accd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3428ae91-e7f3-4e5e-ba5d-cd17759da7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-slider-handle rc-slider-handle-click-focused</value>
      <webElementGuid>8fdfdcd7-0578-484f-852a-a7fc2ce279bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>9166ca5e-baf2-44c5-b0d0-f20a8ac8df05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb200b6d-018f-4a5d-8e14-9b56a31b9751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7a4caead-395c-4d90-af34-0617f5daa8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>66346213-64d2-434c-bf1c-84e1549392f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5565ccfe-af7c-48ba-92f6-d77af6922c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;CustomForm__StyledContainer-sc-106w49f-0 ghkHQs&quot;]/div[@class=&quot;CustomForm__StyledContainerInner-sc-106w49f-1 bdsxPz&quot;]/div[@class=&quot;CustomForm__StyledRow-sc-106w49f-4 iKagmj&quot;]/div[@class=&quot;CustomForm__RateColumn-sc-106w49f-5 gvaWCT&quot;]/div[@class=&quot;rc-slider CustomForm__StyledSlider-sc-106w49f-7 cPQzcu&quot;]/div[@class=&quot;rc-slider-handle rc-slider-handle-click-focused&quot;]</value>
      <webElementGuid>081a4694-7e85-4048-8b32-6a1404ae53db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div/div[4]/div/div/div[2]/div/div[3]</value>
      <webElementGuid>82f5ff71-8c0e-4ae6-a146-c8558135bfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>97faddbf-c783-4525-995d-4446a6664ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
