<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sector-Other</name>
   <tag></tag>
   <elementGuidId>58d317ec-60ac-48e3-9e1d-d7781a2dd840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-12-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'Other')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25a0ab4d-a033-4f2a-8010-cac3bbbad615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-2d7khs-option</value>
      <webElementGuid>e8cc59bc-d142-430a-9f43-4294f1d9097e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-12-option-1</value>
      <webElementGuid>421ccfaf-4d0f-424a-a7d6-22c3f1445251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>90729762-b4e0-483e-8182-4675d6aa54a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other</value>
      <webElementGuid>f6b8b071-0612-4e11-8bd9-abf4b748e0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-12-option-1&quot;)</value>
      <webElementGuid>a7d4ce1a-0bbd-4bd0-a989-df85be304b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-12-option-1']</value>
      <webElementGuid>961811d6-3e77-4675-9b52-64468d5c1c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[5]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>505d57b4-4286-4bb4-87d0-0c18a617e5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Government/Authority'])[1]/following::div[1]</value>
      <webElementGuid>3e7c8605-bc96-4331-b8eb-8c9017d5fbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sector'])[1]/following::div[7]</value>
      <webElementGuid>276c4f30-ec4a-4039-a29d-19565d1dc41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private, Corporate'])[1]/preceding::div[1]</value>
      <webElementGuid>25ead7dd-ff9e-41b2-b133-34288b1e1147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public service, Fed/State Govt'])[1]/preceding::div[2]</value>
      <webElementGuid>97d5aae0-74c0-40ec-90d0-9938639ccb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Other']/parent::*</value>
      <webElementGuid>c9d3c7e4-a045-4a06-812e-91b76778e298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[5]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>301db1cc-f69c-4f7b-84f6-dcbbe169c1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-12-option-1' and (text() = 'Other' or . = 'Other')]</value>
      <webElementGuid>f15d77cc-b59a-4372-b13f-e8a3fd34176f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
