<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_- Chief executive</name>
   <tag></tag>
   <elementGuidId>ec1afe90-1627-443c-ace6-860117046839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-11-option-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-11-option-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37af9d17-ad01-41f4-a862-538b2324d834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-2d7khs-option</value>
      <webElementGuid>27f16dbb-f952-4aa1-9aac-391717f4df6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-11-option-0-0</value>
      <webElementGuid>b25a9d09-9f4a-415d-ae2c-225b180fde59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>42bdf688-000e-44a5-a6d6-9bcfab411a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Chief executive</value>
      <webElementGuid>fb6b2f01-ef12-4253-b37a-34dd2ed8b467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-11-option-0-0&quot;)</value>
      <webElementGuid>cc82fb3d-0438-49c0-9efd-0b6b33e8e67e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-11-option-0-0']</value>
      <webElementGuid>3ab4ac99-2d9a-4c74-bfff-016ca6db6e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div[4]/div/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>7ba68808-87a9-468a-b48a-deccd74b9cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::div[2]</value>
      <webElementGuid>72fb63b7-2b69-4c74-ba4f-b8aa93d9045a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Job Area'])[1]/following::div[9]</value>
      <webElementGuid>bfec63ad-6ec6-48ce-a6f5-a99ddde1081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Administrative or commercial manager'])[1]/preceding::div[1]</value>
      <webElementGuid>451a2101-f360-496d-a595-d06987b50a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Production or specialized services manager'])[1]/preceding::div[2]</value>
      <webElementGuid>d6b68f40-e1cf-4f67-af34-57cde1975121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='- Chief executive']/parent::*</value>
      <webElementGuid>a344126c-feba-4562-95b0-8c6ebf46555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>3b1c8b2a-6b1e-46f5-9a50-1ebb7d2a9774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-11-option-0-0' and (text() = '- Chief executive' or . = '- Chief executive')]</value>
      <webElementGuid>51a97ec3-aac0-4cdf-8823-1fe5e286484f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
