<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Groups</name>
   <tag></tag>
   <elementGuidId>1a5439d3-536d-400f-a132-fc6318e53f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TableTabs__Tab-sc-1b1jhm2-2.iievwS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'TableTabs')][contains(text(),'Groups')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72606b50-49b6-4120-83ee-78a6aa5a24b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TableTabs__Tab-sc-1b1jhm2-2 iievwS</value>
      <webElementGuid>64517144-4bfa-49c8-b6e6-b8f52fed1d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Groups (6)</value>
      <webElementGuid>059e7937-f420-4d87-98ea-bef75798d3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;TableTabs__Wrapper-sc-1b1jhm2-0 ccFpTt&quot;]/div[@class=&quot;TableTabs__MainPart-sc-1b1jhm2-1 imYDAz&quot;]/div[@class=&quot;TableTabs__Tab-sc-1b1jhm2-2 iievwS&quot;]</value>
      <webElementGuid>8cce6ddc-bff9-49f5-9ac1-bcc4aafe385e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[3]/div/div[2]</value>
      <webElementGuid>9258fdab-1e50-42bd-a9af-9d965ca6c42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List (48)'])[1]/following::div[1]</value>
      <webElementGuid>864ccf6d-621f-4d23-bd07-bb6eba7076bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove selected respondents'])[1]/following::div[4]</value>
      <webElementGuid>bc3bea0d-233e-40f0-bffe-a4477354bcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::div[3]</value>
      <webElementGuid>09cfc006-483a-4d71-bd3a-6751f514cf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter type'])[1]/preceding::div[6]</value>
      <webElementGuid>0d7e9d8d-e689-46a6-8e91-fe1bd566ac82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Groups (6)']/parent::*</value>
      <webElementGuid>92b80776-0274-4f4a-8e41-f09a3e9b485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]</value>
      <webElementGuid>d00a7abe-856a-4f70-97ae-25d01f1c53d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Groups (6)' or . = 'Groups (6)')]</value>
      <webElementGuid>44d8db43-98c9-4d08-9f8d-cbcc7d4cbdd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
