<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Respondent Information Tabs</name>
   <tag></tag>
   <elementGuidId>c6363836-0238-4eec-a918-cbfe8645a79f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TableTabs__MainPart-sc-1b1jhm2-1.imYDAz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'EditRespondent__Content')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1b96dcd-6478-49a0-8cfe-0cf9c9960a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TableTabs__MainPart-sc-1b1jhm2-1 imYDAz</value>
      <webElementGuid>05e2c5a0-a892-4f75-bf9c-a6f99eb7a2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Respondent InformationInvites (0)Assessments (0)Reports (0)Groups (0)</value>
      <webElementGuid>8ef1c839-677b-4005-939c-728c650b7e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;EditRespondent__Content-sc-yea5cp-0 bHZBXn&quot;]/div[@class=&quot;TableTabs__Wrapper-sc-1b1jhm2-0 ccFpTt&quot;]/div[@class=&quot;TableTabs__MainPart-sc-1b1jhm2-1 imYDAz&quot;]</value>
      <webElementGuid>292117ad-3718-4790-bf67-8f58623aea4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>3f49d4b4-d938-4ea4-ba20-4957d66921ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::div[11]</value>
      <webElementGuid>4b528215-50be-4fdf-9b5a-fa8a019c7a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>8266c0d9-4b02-4cf0-95d9-9fd584ccc2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Respondent InformationInvites (0)Assessments (0)Reports (0)Groups (0)' or . = 'Respondent InformationInvites (0)Assessments (0)Reports (0)Groups (0)')]</value>
      <webElementGuid>2fe755af-65ed-479e-af89-4c1cd0b39069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
