<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Invitation Id</name>
   <tag></tag>
   <elementGuidId>49237bc2-5621-4ed1-b867-b83839570470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.sc-hmdomO.boyYwH</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=&quot;invitationId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b68fb93f-7d08-40ee-826d-74ced1add297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>7fjuti</value>
      <webElementGuid>d3f54b67-9775-497d-ba1d-54d501d225ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hmdomO boyYwH</value>
      <webElementGuid>63499c1c-3e37-4d8d-8a8a-a632b7d058e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invitation Id</value>
      <webElementGuid>ab0bfd23-b7f1-4254-8ce1-f4238827db2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer eSldpq sc-bmzYkS jIjedo&quot;]/div[@class=&quot;sc-eqUAAy hAjgGB&quot;]/form[1]/div[@class=&quot;sc-dAlyuH kShVME&quot;]/div[@class=&quot;sc-fHjqPf ewXzZn&quot;]/div[@class=&quot;flex-box&quot;]/label[@class=&quot;sc-hmdomO boyYwH&quot;]</value>
      <webElementGuid>80b210c3-01fe-4da8-a923-776425d346b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/label</value>
      <webElementGuid>57ba6801-41ed-4423-bba8-0fd5cf569062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment Session Details'])[1]/following::label[1]</value>
      <webElementGuid>6e4bfed4-64bb-4d12-b3a5-8b4cc0f57084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respondent Id'])[1]/preceding::label[1]</value>
      <webElementGuid>4ee5fa1d-7a80-45ba-85c6-619d58ece9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::label[2]</value>
      <webElementGuid>bf2ebb9c-1f14-43e7-9f93-62b19c7ce292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invitation Id']/parent::*</value>
      <webElementGuid>bbb4fd47-57a0-452a-b9ed-1f49947dc1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d3a4aa0d-cd75-498d-9beb-dc9bbeaff89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Invitation Id' or . = 'Invitation Id')]</value>
      <webElementGuid>a5aaa367-5a37-4b9b-9682-2e6cebc7c483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
