<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Next</name>
   <tag></tag>
   <elementGuidId>3cbccea3-ef21-491f-8cb1-cf7dc67b1218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-bypJrT.kAFndp.next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44b027ee-83c8-4e6c-a56d-328d87aef4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>01fab662-ee1d-40dc-abeb-d783a99f11fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bypJrT kAFndp next</value>
      <webElementGuid>8fedf444-16ea-4955-a8c7-0d223c760ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Press Enter ↵Next</value>
      <webElementGuid>5342bd73-58f9-420d-a006-ae1d98f6d3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer hCtYxp sc-guJBdh iNaETe noPadding&quot;]/div[@class=&quot;sc-fqkvVR hgaxwi&quot;]/div[@class=&quot;sc-klVQfs ccqzuV&quot;]/div[@class=&quot;sc-bypJrT kAFndp next&quot;]</value>
      <webElementGuid>0e0c45ac-ff99-47af-a50d-71254ff0fb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]</value>
      <webElementGuid>d58fa1aa-f222-4554-a0d1-f7670ab013e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[1]</value>
      <webElementGuid>f495c844-9be0-4cc5-bd56-d89e50a67e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>5902f12a-a4b7-4089-849e-02949f49f3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Press Enter ↵Next' or . = 'Press Enter ↵Next')]</value>
      <webElementGuid>3b96dd64-2415-4dd6-9302-69aea92f3f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
