<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Assessment Completed</name>
   <tag></tag>
   <elementGuidId>cb281119-7a75-427e-9b5f-63a4205d57ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[contains(text(),'恭喜您，本次测评已完成。')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.sc-dcJsrY.ORdkI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>668ba9aa-f108-4fc1-a2f7-043dfdc27a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dcJsrY ORdkI</value>
      <webElementGuid>4f69603e-6f2c-4d7b-8ede-5492be296e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assessment Completed</value>
      <webElementGuid>036a6052-af49-4102-8bcc-48cc40899759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer eSldpq sc-btwKTd IplZy&quot;]/div[@class=&quot;sc-eqUAAy hAjgGB sc-gFnajm joLwHk&quot;]/div[@class=&quot;sc-eONNys fOLTYK&quot;]/h1[@class=&quot;sc-dcJsrY ORdkI&quot;]</value>
      <webElementGuid>1be930be-5b6f-4312-a95c-9f821524a389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/h1</value>
      <webElementGuid>53b16d9a-d339-4685-a054-f1f718891305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You may now close the browser tab'])[1]/preceding::h1[1]</value>
      <webElementGuid>68f3cd54-71b6-4b45-bb9b-60e87925187b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assessment Completed']/parent::*</value>
      <webElementGuid>0173fd6f-4e74-49b1-a85d-f37793e52c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d58f4afb-8e4a-4871-b75a-89e844b79c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Assessment Completed' or . = 'Assessment Completed')]</value>
      <webElementGuid>fa1a8499-ab38-47f1-a9c9-6c29627b24fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
