<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Progress</name>
   <tag></tag>
   <elementGuidId>e13c9ece-f2c2-4830-b88f-d7a808bb7609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'完成进度')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-iHbSHJ.bmIaJZ.button > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ef11d81-0534-4009-b0f2-a1620dce493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Progress  </value>
      <webElementGuid>80f2de2e-3a48-4a20-b0ee-193550507f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lang-wrapper ltr&quot;]/div[@class=&quot;sc-gEvEer hCtYxp sc-iQbOkh goFlKk&quot;]/div[@class=&quot;sc-lcIPJg fklRvC&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;sc-bcSKrn gyCvvh&quot;]/div[@class=&quot;sc-iHbSHJ bmIaJZ button&quot;]/span[1]</value>
      <webElementGuid>89c6d5cf-9e35-438a-a90d-d2a9a74da937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/div/span</value>
      <webElementGuid>1850e0db-361f-4382-b3fc-5c903226d162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[1]/following::span[1]</value>
      <webElementGuid>f0283eff-b2d9-4749-9e16-19fe0689c662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='?'])[1]/following::span[1]</value>
      <webElementGuid>8f365d9f-53ae-45ef-8682-7605b1959737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::span[2]</value>
      <webElementGuid>3947dd64-ca8c-4236-8c09-2e5c4e38eb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Response is required'])[1]/preceding::span[2]</value>
      <webElementGuid>316f7f3f-fd3f-4bf6-a1a8-2bb4a8d88585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Progress']/parent::*</value>
      <webElementGuid>6561c1f5-01da-4155-b806-ab0a7eb32fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/span</value>
      <webElementGuid>f1bc64cc-3700-4cbe-8f5a-7b9b6a05f3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Progress  ' or . = 'Progress  ')]</value>
      <webElementGuid>ecaf99cc-dc19-4081-8a48-9a3dab0af6c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
