<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ideal profile type</name>
   <tag></tag>
   <elementGuidId>3b2b1489-c829-45d4-9bca-ebe508e31112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.IdealProfileScales__DescriptionRow-sc-1skdrq0-0.jXXtcc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'IdealProfileScales__DescriptionRow')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4e1536dd-0995-4b3c-888a-ecdcb34437da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IdealProfileScales__DescriptionRow-sc-1skdrq0-0 jXXtcc</value>
      <webElementGuid>10b04d65-08af-43df-b27d-706861873224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ideal profile type:Manually configured</value>
      <webElementGuid>bb93e5ae-d285-4757-8e40-8ba15af20d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;IdealProfileScales__DescriptionRow-sc-1skdrq0-0 jXXtcc&quot;]</value>
      <webElementGuid>27ef6cc5-6f73-48bc-af9d-e00c2d0faa2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>52b7bab9-de3f-41e0-869b-602a0d15edc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[1]</value>
      <webElementGuid>e075d40e-1911-4152-b5cb-cb05e1a9c027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Manually Configured'])[1]/following::div[2]</value>
      <webElementGuid>ef8f7c18-d59b-47e3-a57d-19151ec19f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]</value>
      <webElementGuid>ca84bea6-6b7e-47e5-ac25-45a9fbdbe91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ideal profile type:Manually configured' or . = 'Ideal profile type:Manually configured')]</value>
      <webElementGuid>4e912904-92ad-4d37-b57f-9519703d9a66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
