<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Answer</name>
   <tag></tag>
   <elementGuidId>de7d076f-afbe-48f0-a61f-082cfbc5ea46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.AnswersStep__AnswerItem-sc-1j3ra9h-6.cYQYDg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'AnswersStep__QuestionsColumn')][1]//div[contains(@class,'AnswersStep__QuestionItem')][1]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ece1dce-5c16-485f-9760-df0ced8d7c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AnswersStep__AnswerItem-sc-1j3ra9h-6 cYQYDg</value>
      <webElementGuid>405a5b57-d4ba-4f6d-a501-ee71391b5cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>478361f5-7882-4646-b007-24b423a9fe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 bASsOq AnswerSheet__StyledModal-sc-rvlq9v-0 hMpMwJ&quot;]/div[@class=&quot;AnswerSheet__Content-sc-rvlq9v-1 ylJae&quot;]/div[@class=&quot;AnswersStep__TestQuestionsWrapper-sc-1j3ra9h-0 jmUxIg&quot;]/div[@class=&quot;AnswersStep__ColumnsWrapper-sc-1j3ra9h-1 katlYt&quot;]/div[@class=&quot;AnswersStep__QuestionsColumn-sc-1j3ra9h-2 BAKlT&quot;]/div[@class=&quot;AnswersStep__QuestionItem-sc-1j3ra9h-3 jNORZg&quot;]/div[@class=&quot;AnswersStep__AnswersWrapper-sc-1j3ra9h-5 jfnlXI&quot;]/div[@class=&quot;AnswersStep__AnswerItem-sc-1j3ra9h-6 cYQYDg&quot;]</value>
      <webElementGuid>f4666f87-d03b-496a-9998-537eae951ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/div[3]/div/div/div/div/div[2]/div</value>
      <webElementGuid>bf065a77-9fcb-428b-a0bb-c9fc370fb644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='answers'])[1]/following::div[8]</value>
      <webElementGuid>d12d5cc4-3f2d-4022-9c94-b4df210d5a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='assessment'])[1]/following::div[9]</value>
      <webElementGuid>677b96bf-4016-4774-811b-fe6b8f5322be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respondent'])[1]/preceding::div[1001]</value>
      <webElementGuid>f3cd42fe-e53f-4eac-b166-26b18d9721c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[1002]</value>
      <webElementGuid>35b80658-7173-4bed-a11d-be257db6c5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div/div/div[2]/div</value>
      <webElementGuid>ac813835-1121-490a-adb9-100ac1ed4c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>f34e6184-99db-4ae9-805b-7db48af738f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
