<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Settings Menu</name>
   <tag></tag>
   <elementGuidId>abec8513-201c-4742-b2b8-ea64d3a6c454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/settings&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02403837-a44c-4e36-b2d5-9cf7783d002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>from</name>
      <type>Main</type>
      <value>/respondents</value>
      <webElementGuid>1bfce440-7b5d-4282-a6c5-ae371c3a459c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isactive</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>211d86ef-c2db-4e2d-9ec6-40e54d84d65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Sidebar__StyledTab-sc-h8wc3d-4 dValNY</value>
      <webElementGuid>4245fa13-91bb-4a07-a1d8-4fea7dbd23ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/settings</value>
      <webElementGuid>8637d71e-d2e6-46d0-9be1-26998b93306b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
      <webElementGuid>d04a6052-2f69-4859-a706-b3b532a85b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/nav[@class=&quot;Sidebar__SidebarContainer-sc-h8wc3d-1 gwowdB&quot;]/div[@class=&quot;Sidebar__TabsList-sc-h8wc3d-2 gUAEly&quot;]/div[1]/a[@class=&quot;Sidebar__StyledTab-sc-h8wc3d-4 dValNY&quot;]</value>
      <webElementGuid>27f06af2-1113-45e5-bed5-30f2ea4ece6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/nav/div/div/a[5]</value>
      <webElementGuid>749052fe-40ed-4211-bcb5-8db70456a15f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::a[1]</value>
      <webElementGuid>f0c3778b-3b9a-4189-b0c3-91f156d14bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invites'])[1]/following::a[2]</value>
      <webElementGuid>6d9ff3f3-65c2-4bad-8cdf-b26da99e5195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits balance:'])[1]/preceding::a[1]</value>
      <webElementGuid>02fdc47c-caaf-4d85-a185-fc18b5f28fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/settings')]</value>
      <webElementGuid>5f1606cf-ef73-4c79-8dbd-9909b1cfe475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>db0a3385-9825-4e40-9a83-45d8194b63d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/settings' and (text() = 'Settings' or . = 'Settings')]</value>
      <webElementGuid>8c766f52-d4fb-4f25-a41b-d132f3719de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
