<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rating</name>
   <tag></tag>
   <elementGuidId>f67388e1-2db8-455a-a700-49ae6c0d073c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-slider-handle.rc-slider-handle-click-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>055ff2fe-d78d-4b0d-b00c-c2306b0c3350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ea2fe1c-732f-4c9c-9732-a80c9dc4782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-slider-handle rc-slider-handle-click-focused</value>
      <webElementGuid>9d82d3c1-c6c5-47c4-8c4d-adee6fa3d55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>b99b3d5c-69bb-4f73-8fc0-c93bbc4bed1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7e7c8679-a200-4d06-8f3b-6d91d4295df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>83443b6f-ec19-4bea-89c5-a6f07a3efe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ddeed2e9-19d4-49aa-8f79-e05de1f099be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>776a696a-2305-4c27-bff0-1ddec6cd7c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;IdealProfileScales__ScalesWrapper-sc-1skdrq0-1 bfXtbD&quot;]/div[@class=&quot;IdealProfileScales__ScaleItem-sc-1skdrq0-2 jISlaI&quot;]/div[@class=&quot;IdealProfileScales__ScaleEdit-sc-1skdrq0-4 ktVelc&quot;]/div[@class=&quot;rc-slider IdealProfileScales__StyledSlider-sc-1skdrq0-7 dJlUKz&quot;]/div[@class=&quot;rc-slider-handle rc-slider-handle-click-focused&quot;]</value>
      <webElementGuid>2f4bc665-4963-47ea-a3e1-ec88f424c749</webElementGuid>
   </webElementProperties>
</WebElementEntity>
