<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Request</name>
   <tag></tag>
   <elementGuidId>bc117dd4-16a3-4039-83d5-89046790cccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ReportsList__Footer-sc-6mp1m1-9.lnDKED > button.Button__BaseButton-sc-3twruo-0.Button__PrimaryButton-sc-3twruo-1.lfZVwD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,'Button__BaseButton')]//span[contains(text(),'Request')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e60b442c-f2be-458b-993f-05be46c0c10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2b9f250-52f1-47af-8af7-f0941e0b95bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD</value>
      <webElementGuid>10653319-c5dc-447b-ac3d-9c2c39f2d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request</value>
      <webElementGuid>a89ecb6a-78a3-4116-9f54-166d698f19fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 bASsOq RequestReportModal__StyledModal-sc-4yx7so-0 ijgFBL&quot;]/div[@class=&quot;RequestReportModal__Container-sc-4yx7so-1 fBEVwy&quot;]/div[@class=&quot;ReportsList__Container-sc-6mp1m1-0 dzbYrr&quot;]/div[@class=&quot;ReportsList__Footer-sc-6mp1m1-9 lnDKED&quot;]/button[@class=&quot;Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD&quot;]</value>
      <webElementGuid>2b705ad6-cf3c-42fb-b339-76f45975a029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/div[3]/div/div[4]/button</value>
      <webElementGuid>56430275-2fd4-449d-99ae-1d15b3870e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits balance:'])[2]/following::button[1]</value>
      <webElementGuid>8f2445fa-9422-49c3-ac5a-c537e92896b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total credits:'])[1]/following::button[1]</value>
      <webElementGuid>a6910704-1384-4292-80c5-286ec344aa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/button</value>
      <webElementGuid>fcee76d8-badb-4401-a277-14235dc12664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request' or . = 'Request')]</value>
      <webElementGuid>9a337e97-fe93-41a3-8749-93f3e56ebc3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
