<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invitation Id_respondentId_1</name>
   <tag></tag>
   <elementGuidId>e4ead890-a2f2-48d5-b738-63643b0c6c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#0b2irj</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='0b2irj']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a46660de-e6a0-4813-8d7b-98bc2a0894be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b703d11d-26f4-4351-b061-a6ba13086ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0b2irj</value>
      <webElementGuid>be42b95a-01a8-4d29-b163-71a150af49b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5a9f4caf-2c68-4063-9f8d-8c001b3b3678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>respondentId</value>
      <webElementGuid>569ddf97-1f4e-4775-bebc-0f08cd3c4328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eDPEul WbSWh</value>
      <webElementGuid>cdff96b2-5922-4d38-a66a-38c37bf84ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>direction</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>eaace0e0-58ef-4779-89cb-fbde1213293b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0b2irj&quot;)</value>
      <webElementGuid>9be59409-06cc-47ca-a0e6-947dff1bbaea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='0b2irj']</value>
      <webElementGuid>e22518b7-abc1-4159-bce4-f61e956ed485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>194bc7f2-a848-4f65-86f2-193b6db2f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c695f63e-071e-4def-8a62-71eb9034cc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '0b2irj' and @name = 'respondentId']</value>
      <webElementGuid>e4474ff1-5dea-4c11-9263-0b361bc3cb73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
