<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>598e4117-71c9-47fd-b4ea-5a990c4e3009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Input__Container-sc-1cu1w4j-0.giaEKD.ManageGroupDetails__Input-sc-17of4k6-2.jeaEIF > div.Input__InputWrapper-sc-1cu1w4j-1.hJxVlQ > input.Input-sc-1cu1w4j-2.jNDyqd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'ManageGroupDetails')]//input[@placeholder=&quot;Name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5626f65b-f54e-4df1-bf65-4c6cc0776f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>c6f432f9-9d86-4a1d-9440-67fb8cdc9c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1cu1w4j-2 jNDyqd</value>
      <webElementGuid>6b98eb05-7803-4858-a22e-186293d75f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Auto Group 0701035709</value>
      <webElementGuid>5092a5ed-4556-448e-bfa8-a9d734688f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 cDYLtF ManageGroupDetails__Modal-sc-17of4k6-0 igjOTl&quot;]/div[@class=&quot;ManageGroupDetails__Content-sc-17of4k6-1 crbyNJ&quot;]/div[@class=&quot;Input__Container-sc-1cu1w4j-0 giaEKD ManageGroupDetails__Input-sc-17of4k6-2 jeaEIF&quot;]/div[@class=&quot;Input__InputWrapper-sc-1cu1w4j-1 hJxVlQ&quot;]/input[@class=&quot;Input-sc-1cu1w4j-2 jNDyqd&quot;]</value>
      <webElementGuid>69f822b0-f8f9-493c-9f8a-02c68a8e5dfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Auto Group 0701035709']</value>
      <webElementGuid>9930277a-aabc-432e-8cd7-60a3b17c7e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[6]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>a216240b-a536-4b14-9e05-d8258e1729b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>e8bb249c-f6e4-4e08-9218-f37599238036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Name']</value>
      <webElementGuid>8af857dd-85e0-434e-8c9e-df5d93b7d7a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
