<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_company</name>
   <tag></tag>
   <elementGuidId>814a6616-7b5f-4dc9-b4c2-8d2ecd8ad823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29c3ff55-331b-431a-a963-64dc317b581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company Name</value>
      <webElementGuid>b73e2f82-32e0-42db-8524-00e8eeeb1228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>d50bb907-529a-428c-b680-a9a1d4993932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Input-sc-1cu1w4j-2 jNDyqd</value>
      <webElementGuid>0d674d74-29de-418b-8a09-b8121d75c46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>0c118d98-6f23-4e1e-80df-829cc4e37628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>86e06bbb-ac6e-43f9-be0f-8ec408697f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company']</value>
      <webElementGuid>f27ca3f9-6a1a-4748-a35e-b59228512ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[8]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>efcabc41-669f-4cf4-92f4-700c0fc6850b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>3ce2b114-57d2-4e3b-a352-cf1b8ee67901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Company Name' and @id = 'company']</value>
      <webElementGuid>8282d3ab-1a8e-4f4b-bd7d-97cb80ff3ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
