<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>241f51a2-9a6e-41ef-9750-da0e998b4d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button__BaseButton-sc-3twruo-0.Button__PrimaryButton-sc-3twruo-1.lfZVwD.ManageGroupDetails__Button-sc-17of4k6-4.dSVTzn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'ManageGroupDetails')]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfda0e94-3549-4a19-8ab9-0c133530bbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ecb54242-35a2-4881-a100-91a2dc05c50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD ManageGroupDetails__Button-sc-17of4k6-4 dSVTzn</value>
      <webElementGuid>b5b51822-74ca-44b9-adf9-3b69dc9c16eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>758ce6a5-f167-4ab5-826a-c431380b40e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;rodal rodal-fade-enter&quot;]/div[@class=&quot;rodal-dialog rodal-fade-enter&quot;]/div[@class=&quot;NewModal__Container-sc-1b0fhaf-0 cDYLtF ManageGroupDetails__Modal-sc-17of4k6-0 igjOTl&quot;]/div[@class=&quot;ManageGroupDetails__ButtonsWrapper-sc-17of4k6-3 jjrWLN&quot;]/button[@class=&quot;Button__BaseButton-sc-3twruo-0 Button__PrimaryButton-sc-3twruo-1 lfZVwD ManageGroupDetails__Button-sc-17of4k6-4 dSVTzn&quot;]</value>
      <webElementGuid>a9b8ba09-400c-43e9-b595-c035e36a4ee2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[6]/div[2]/div/div[3]/button</value>
      <webElementGuid>96dd04ad-60ee-40fb-bf5f-40b5d4f15fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::button[1]</value>
      <webElementGuid>8cf9bf0b-ba81-406f-9dbe-1c54002ce6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::button[1]</value>
      <webElementGuid>b25c1556-78a4-4658-a764-4195fe92844f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete group'])[1]/preceding::button[1]</value>
      <webElementGuid>e96c709d-4402-453d-9d94-af9d5e23078a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>2af61ce8-1c7f-456e-99ff-6a736c314ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>58d9dac2-24a0-4d02-a3c0-46b7a3221907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
