<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>779d4d8e-5c6b-4077-8de1-b33df21ccb9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.Search__SearchInput-sc-11r4swm-1.cfSKyc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@placeholder,&quot;Search&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c275ac36-6a8d-4db4-b50c-fd090d9207a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>260fe797-ef0d-4930-b0a2-4af1ee06f192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Search__SearchInput-sc-11r4swm-1 cfSKyc</value>
      <webElementGuid>02996038-3291-46ee-b5ca-466a5fae2c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>jjscabangon+0605035136@gmail.com</value>
      <webElementGuid>54900648-dafe-4dc3-a6ae-c1fbc0c4d803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;ContentRouter__Container-sc-ayudpc-0 kFILiX&quot;]/div[@class=&quot;ContentRouter__ContentContainer-sc-ayudpc-1 bDzahg&quot;]/div[@class=&quot;ContentRouter__StyledRouter-sc-ayudpc-2 cdCFNr&quot;]/div[@class=&quot;ContentRouter__RouteWrapper-sc-ayudpc-3 fVaimK&quot;]/div[1]/div[@class=&quot;PageWrapper__Container-sc-10mepnc-0 eLXHhm&quot;]/div[@class=&quot;AdvancedFilter__Wrapper-sc-90morx-0 didgyb&quot;]/div[@class=&quot;Search__AppliedFiltersContainer-sc-11r4swm-0 cfvCUf&quot;]/input[@class=&quot;Search__SearchInput-sc-11r4swm-1 cfSKyc&quot;]</value>
      <webElementGuid>ba3a21f6-46cb-441e-9890-16d3d5c4bcd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='jjscabangon+0605035136@gmail.com']</value>
      <webElementGuid>432faa83-d246-40ae-9ef2-7cdc7e68233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>f88cbb12-d6d2-40e5-a92e-49364b001a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b7096f57-4312-4ff5-af9d-d10217239c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search']</value>
      <webElementGuid>9ebbef75-088e-45a5-875c-090535ca5334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
